# Generated by Django 4.2.4 on 2023-12-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_coupon_order_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='amount',
        ),
        migrations.AddField(
            model_name='coupon',
            name='duration',
            field=models.CharField(choices=[('once', 'Once'), ('repeating', 'Repeating')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='percent_off',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='stripe_coupon_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
