# Generated by Django 4.2.4 on 2023-12-23 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_coupon_amount_coupon_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vorname', models.CharField(max_length=255)),
                ('nachname', models.CharField(max_length=255)),
                ('bezirk', models.CharField(max_length=255)),
                ('street_address', models.CharField(max_length=255)),
                ('hausnummer', models.CharField(max_length=255)),
                ('plz_zip', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('telefon', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('um_hinweise', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='user_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.user_details'),
        ),
    ]
