# Generated by Django 4.2.8 on 2023-12-24 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_order_stripe_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='image',
            field=models.FileField(upload_to='img/food/'),
        ),
    ]
