# Generated by Django 4.2.8 on 2023-12-24 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_menu_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='image',
            field=models.FileField(upload_to='assets/img/food/'),
        ),
    ]
