# Generated by Django 4.2.4 on 2023-12-30 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_menu_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='image',
            field=models.FileField(upload_to='menu_images'),
        ),
    ]
